### PR TITLE
open server url on webpack dev server start

### PR DESCRIPTION
**Pull request by maddhruv**
- Dependencies add - opn (dev)

### CODE REVIEW

**Comment by akiran** [comment]
@maddhruv Can you check why tests are failing ?

**Comment by maddhruv** [comment]
> Can you check why tests are failing ?

sure

**Comment by maddhruv** [comment]
@akiran it is from the test suites
Not caused by my commit

**Comment by akiran** [comment]
@maddhruv Yes, Its not because of your commit.

Can you you debug why tests are failing, so that we can make sure in future PR's test are passing before merging them

**Comment by maddhruv** [comment]
> Can you you debug why tests are failing

Sure, will do a PR

**Comment by maddhruv** [comment]
this can be merged?

**Pull request merged**
