### PR TITLE
adds support for fractional `slidesToShow`

### PR DESCRIPTION
**Pull request by gbrassey**
allows fractional values in the `slidesToShow` option

### CODE REVIEW

**Comment by robcolburn** [comment]
`slick-carousel` seems to allow "peeking" while still using integers as slidesToShow.
http://kenwheeler.github.io/slick/

See Examples:
* Variable Width
* Center Mode
* Slider Syncing

I'm not really advocating one approach or another, but this project seeks parity with `slick-carousel`.
https://github.com/akiran/react-slick#road-to-10

**Comment by gbrassey** [comment]
Yes. I realize now that I was having trouble because I was using React elements as direct children to the `Slider` and not applying the `style` prop (which passes the slide width). I think this pull request can be closed, although I wonder if there is anyway to protect against this type of developer error?

**Comment by robcolburn** [comment]
React PropTypes doesn't distinguish integers vs numbers :/. But, we could add a custom validation in propTypes

https://facebook.github.io/react/docs/reusable-components.html

**Comment by gbrassey** [comment]
I was thinking more along the lines of ensuring that the width of the slides is set by react-slick, even if the direct children of the `Slider` element are other react components. 




The problem arose because my slide components did not set the style that is passed to them by react-slick in the props (ie. `<slideComponent style={this.props.style}>`). I solved the problem by wrapping the `slideComponent` in `div`'s. I see `React.cloneWithProps` is being used to render the slides but it was not setting the width without explicitly declaring it in jsx.

**Pull request closed without merging**
