### PR TITLE
Added Lightbox Mode

### PR DESCRIPTION
**Pull request by aaronholla**
Hi, 

I added a very basic Lightbox mode to the slider to be able to click on a slide and have it open in a popup box. This is very similar to #870 ( #893 ) adding a Fullscreen mode, except it doesn't force you into fullscreen it will instead give you a window with the slider in it. I added css classes for the lightbox to allow for further customization around overlay color and animating the opening of the lightbox.

| CSS Class | Description | lightbox
| ----- | ---- | ---- |
| .slick-wrapper | A wrapper div is always there even when lightbox is disabled | True/False
| .slick-lightbox-overlay | A container div for the lightbox | True
| .slick-lightbox | The actual div that will be the lightbox | True
| .slick-lightbox.open | Lightbox div will get an open class added when it is opened | True

Changelist
----

-Added "lightbox" prop to the slider 
-Added "lightboxOpen" state to the slider
-Added stopPropagation to all clickHandlers ( this prevents triggering the close lightbox )
-Added refs for wrapper & lightbox
-Added clickHandler to track slides for triggering lightbox if enabled
-Added example to the docs
-Added example styles for lightbox to function
-Added lightbox prop to the Readme

----

**Known bugs**
- When lightbox open and you maximize or minimize the window the slides are not the correct size and position. Resizing the window seems to fix this. Not sure what is causing this if it is a CSS issue or something I need to update.
- May have to add an update or something somewhere for AutoPlay to work properly 
- Wrapper trys to keep its size when lightbox is open. Noticed if there are margins on the slider that the wrapper ignores these margins and ends up smaller then it should be cause the HTML on the page to collapse by the size of the margins when lightbox is open
----
P.S.
_I could also expose a new method to toggle the lightbox. This would allow people to do things like create their own buttons to trigger the lightbox. Also would allow for a close button to be added by the user. ( think x in the corner if you wanted to style this like a fullscreen option )_

### CODE REVIEW

**Comment by aaronholla** [comment]
Also for the tests I have to update all of the snapshots now because they will all get that new wrapper div.

I started some tests of the lightbox but haven't had time to fully build out the tests. I would like to add some tests to be sure that it plays well with other settings enabled.

**Comment by akiran** [comment]
Lightbox is not supported by original slick library
http://kenwheeler.github.io/slick/

We can't accept this PR to keep API compatibility with slick

**Comment by aaronholla** [comment]
I understand. Thank you!

**Comment by MihaiWill** [comment]
@aaronholla I am looking for this feature thanks! I will give it a try, I hope is still compatible

**Pull request closed without merging**
