### PR TITLE
Fix wrong if statement related with autoplay and resize

### PR DESCRIPTION
**Pull request by satazor**
This fixes the slider not autoplaying after a resize.

### CODE REVIEW

**Comment by dav92lee** [comment]
+1

**Comment by gregnb** [comment]
+1

**Comment by benji06000** [comment]
+1

**Comment by dsoriano** [comment]
+1

**Comment by mplis** [comment]
+1

**Comment by jitenderchand1** [comment]
Please merge it

**Comment by mjaltamirano** [comment]
+1

**Comment by jasoncarty** [comment]
+1

**Comment by naimulhaider** [comment]
+1

**Comment by vagnercsouza** [comment]
+1

**Comment by ozluy** [comment]
If you dont want to wait for an update following snippet solved my problem with Internet Explorer 

```jsx
componentDidMount() {
        setTimeout(() => {
            this.slider.slickNext()
        },
            4000);
    }

<Slider ref={c => this.slider = c} >
            ...
</Slider>

```

**Comment by Exomnius** [comment]
Can this be merged? @akiran

**Comment by audifaxdev** [comment]
Is this going to get merged one day? cheers !

**Comment by jasonreed7** [comment]
+1

**Comment by danmo** [comment]
+1

**Comment by RusinovAnton** [comment]
@akiran can't believe it isn't merged already.

**Comment by sidoruk-sv** [comment]
Is this project already abandoned?

Or this lib is too big and buggy to be able to handle all of that and it's better to find new fresh and inspired maintainer that can handle all of the exhausting problems. And maybe completely rewrite this project (it will be huge challenge, because of tons of features presented here)?

**Comment by jarzuaga** [comment]
@akiran Read you're doing a new release on npm soon. Any chance you could include this?

**Comment by akiran** [comment]
Yes, I will try to include this

**Pull request merged**
