### PR TITLE
added breakpoint on element reasize support

### LINKED ISSUE #1211: Responsive breakpoints per element's width and not window's width
The responsive `breakpoint` is set according to the windows's width and not the element's width.
#1159 attemped to address this issue i think, but it's closed.

For example, if i have an element or a parent with a width of `300px`, and these breakpoints:  
```
responsive: [
        { breakpoint: 350, settings: { slidesToShow: 1 } },
        { breakpoint: 500, settings: { slidesToShow: 2 } },
        { breakpoint: 800, settings: { slidesToShow: 3 } },
        { breakpoint: 1800, settings: { slidesToShow: 3 } },
      ]
```
The expected behavior is that it will always show 1 slide, 
But it will set the `breakpoint` according to the window's `width` and can display 3 or 4 slides.
[live Example.](https://codesandbox.io/s/km1j830ror)
Code snippet:  
```
class ReactSlickDemo extends React.Component {
  render() {
    var settings = {
      responsive: [
        { breakpoint: 350, settings: { slidesToShow: 1 } },
        { breakpoint: 500, settings: { slidesToShow: 2 } },
        { breakpoint: 800, settings: { slidesToShow: 3 } },
        { breakpoint: 1800, settings: { slidesToShow: 3 } },
      ]
    };
    return (
      <div className="container" style={{ width: '300px' }}>
        <Slider {...settings}>
          <div>
            <img src="http://placekitten.com/g/400/200" />
          </div>
          <div>
            <img src="http://placekitten.com/g/400/200" />
          </div>
          <div>
            <img src="http://placekitten.com/g/400/200" />
          </div>
          <div>
            <img src="http://placekitten.com/g/400/200" />
          </div>
        </Slider>
      </div>
    );
  }
}
```

**Update**
When i look at [this code](https://github.com/akiran/react-slick/blob/48c93ed36cfb58991e6bf4d34a1a588094281d12/src/slider.js#L53) i realize that we might not be able to achieve this with the current setup.
While using `enquire.js` we set a `breakpoint` according to the screen's `width` and not according to the element's `width`.
We need a different or another approach to listen to the element's resize event.

### PR DESCRIPTION
**Pull request by sag1v**
Should fix #1211 and #1159

### CODE REVIEW

**Comment by sag1v** [comment]
Can anyone review this please?

**Comment by tmbdrogba** [comment]
+1

**Comment by imjoshdean-tc** [comment]
@akiran?

I really want to use this project but it feels like it isn't really being actively maintained, especially if this PR gets approved. When can we get this reviewed and merged?

**Comment by imjoshdean-tc** [comment]
Personally I've given up on this package. If I were you @sag1v I would fork it and just use it yourself.

**Comment by sag1v** [comment]
@imjoshdean-tc I am using my own fork with my PR for the past 8 months, i got it on npm under the name `react-slick-rtl` (it started with another bug i solved with `RTL`  support).

I decided to write my own package (not related to `slick` though).

**Pull request closed without merging**
