### PR TITLE
fix Inactivity cause slides to disappear problem

### PR DESCRIPTION
**Pull request by lancehub**
fix https://github.com/akiran/react-slick/issues/202

### CODE REVIEW

**Comment by edygar** [comment]
Any news? This pull-request just fixed my problem, It would be nice if it was merge

**Comment by madsobel** [comment]
I can confirm that this solves #202. +1 for merging it

**Comment by akiran** [comment]
@lancehub  Can you resolve merge conflicts

**Comment by lancehub** [comment]
@akiran OK, I will resolve it.

**Comment by lancehub** [comment]
@akiran conflect resolved.

**Comment by madsobel** [comment]
Okay. This works like a charm. @akiran When can we hope for a new release with this to npmjs.org? :-)

**Comment by akiran** [comment]
@lancehub  There is problem with this fix.
Autoplay demo is rolling over when it reaches the last slide.

**Pull request merged**
