### PR TITLE
Fix issue when clicking prev/next faster than currentSlide is re-calc…

### PR DESCRIPTION
**Pull request by mortentangen**
`targetSlide` is not always simply the next increment, it could be an infinite positive/negative number if the user clicks fast enough on the prev/next arrows (this is easily done if there exists more than a few slides, since the animation seems to go much faster)

Result after going bananas on the next arrow without this fix:
image

### CODE REVIEW

**Comment by Cunha44** [comment]
+1

**Comment by akiran** [comment]
@mathisonian  This fix didn't solve the problem completely .

I checkout you code and clicked on next button of first demo very fast. 
Still I see white screen

**Comment by mortentangen** [comment]
Yes, it doesn't seem like the cloning of slides is fast enough to avoid seeing the white screen, but with this fix at least you won't get stuck with a white screen when you finish clicking.

**Comment by akiran** [comment]
ok.  I will try to fix the white screen issue.

**Comment by dijonkitchen** [comment]
Any update on this?

**Pull request closed without merging**
