### PR TITLE
Before change current slide

### LINKED ISSUE #1216: oldIndex parameter is always undefined in beforeChange function
version:
0.23.1

description: 
the parameter oldIndex in function beforeChange(oldIndex, newIndex) is always undefined 

example : https://codesandbox.io/s/x7x1jp6pnp

What is expected?
oldIndex should be equal to the current slide number

What is actually happening?
oldIndex is always undefined

### PR DESCRIPTION
**Pull request by randallreedjr**
Fixes #1216 
Could use an updated test in `__tests__/beforeChange.test.js`

### CODE REVIEW

**Comment by yoyo837** [comment]
I can hardly wait for this.

**Comment by adenj** [comment]
Any update on when this will be merged in?

**Comment by sprsam** [comment]
Can this be merged since it's been reviewed? @dominicrico @randallreedjr

**Comment by randallreedjr** [comment]
@sprsam Still says "At least 1 approving review is required by reviewers with write access." for me.

**Comment by szklanko** [comment]
Any info when changes will be merged ?

**Comment by florianchevallier** [comment]
@akiran could you please merge this ? It's really breaking for me

**Comment by yoyo837** [comment]
@florianchevallier He may not have noticed this.

**Comment by dominicrico** [comment]
Sorry guys, I can't do anything... We have to wait or you get the package from my fork.

**Comment by TatsuyaYamamoto** [comment]
The changes look good to me.
Only this repo's contributors can add a review?

Sorry, I don't check CONTRIBUTING.md thoroughly .

**Comment by firestar300** [comment]
Any news ?

**Comment by adaniliuk** [comment]
@randallreedjr thanks a lot for the fix. This is the only thing stopping us from update to the most recent react-slick version. Would be great to have it merged as soon as possible.

**Comment by akiran** [comment]
published 0.23.2 with this fix

**Pull request merged**
