### PR TITLE
Fix a bug where autoplaying carousel would lock indefinitely when bro…

### PR DESCRIPTION
**Pull request by mll**
…wser window is resized during automatic slide change.

### CODE REVIEW

**Comment by scriptype** [comment]
:+1:

**Comment by mll** [comment]
@akiran

**Comment by akiran** [comment]
Fixed this in react-slick@0.11

**Comment by chadhahn** [comment]
This seems broken (again?) in 0.12.2. What was the fix for 0.11 if it wasn't this PR from @mll?

**Pull request closed without merging**
