### PR TITLE
Bugfix around handling calculation of slickList width

### PR DESCRIPTION
**Pull request by sbussetti**

### CODE REVIEW

**Comment by developer-lindner** [comment]
Any chance that this will be merged soon?

**Comment by developer-lindner** [comment]
bildschirmfoto 2018-03-05 um 17 21 03

**Comment by laveesingh** [comment]
PR couldn't be merged due to conflicts and introduction to additional prop. Though, effective changes such as using slickList width for slideWidth calculation, have been taken into account.
Thanks!

**Comment by sbussetti** [comment]
fair enough!

**Pull request closed without merging**
