### PR TITLE
Don't allow to be left blank spaces on the end of the scroller

### PR DESCRIPTION
**Pull request by rafaelteixeira**

### CODE REVIEW

**Comment by akiran** [comment]
@rafaelteixeira Thanks for PR.  I will review it soon

**Comment by bvasko** [comment]
Hi! Do you plan on merging this PR? Thanks!

**Comment by akiran** [comment]
Yes,  I will merge it soon.



On Sat, Feb 6, 2016 at 12:42 AM, Bonnie DiPasquale <notifications@github.com

**Comment by rafaelteixeira** [comment]
Hey, any chance that we can merge this PR, or do you prefer that I apply some change before? Thanks!

**Comment by jakeaaron** [comment]
Is this going to be fixed? Would love to see this feature! I dislike the ability to continue scrolling through blank space.
Thanks so much for this carousel port! It's great :)

**Comment by kiddinho1** [comment]
+1

**Comment by atuetek** [comment]
+1

**Comment by akiran** [comment]
I will review it this week

**Comment by aviav** [comment]
+1

**Comment by rafaelteixeira** [comment]
+1?

**Comment by superfunkminister** [comment]
+1

**Comment by calebo** [comment]
@akiran Is this good to merge?

**Pull request closed without merging**
