### PR TITLE
Fixes warning: Unknown props `currentSlide`, `slideCount` on <div> tag

### PR DESCRIPTION
**Pull request by maslianok**

### CODE REVIEW

**Comment by cristianst** [comment]
Can someone please check and merge the PR.

**Comment by stevemao** [comment]
The change LGTM but I wonder if it's easy to add a test...

**Comment by johntron** [comment]
^---- that's a patch build for anyone that needs it: `npm install https://github.com/johntron/react-slick/archive/0.14.6-patch.tar.gz`

**Comment by jarzuaga** [comment]
When is this going to be merged?

**Comment by fandy** [comment]
LGTM the warning appears out the box.

**Comment by michalhartwich** [comment]
merge it, please 🙏

**Comment by tonyDx** [comment]
merge it, please 🙏

**Comment by akiran** [comment]
Fixed this in 0.14.7

**Comment by tonyDx** [comment]
haha,thanks i have updated it today

**Pull request closed without merging**
