### PR TITLE
Fix for issue #628

### PR DESCRIPTION
**Pull request by nelsieborja**
Added explanation inside code for the change made

### CODE REVIEW

**Comment by davincho** [comment]
@akiran Do you think you can merge this PR?

**Comment by gajus** [comment]
@akiran can you add more developers to the repository?

**Comment by abumusamq** [comment]
what's the update on this? @akiran

**Comment by patrickus** [comment]
Would be great to have this fixed, definitely an issue on mobile! @akiran

**Comment by laveesingh** [comment]
All the lazyLoad related issues have been fixed. Please let me know if you think otherwise.

**Pull request closed without merging**
