### PR TITLE
feat: add support for setting autoplaySpeed in the each slide individually

### PR DESCRIPTION
**Pull request by vishwanatharondekar**
We have a requirement where we need to set different autoplaySpeed to each slide depending on type of the slide.

I am not sure whether you will want to keep this as a part of the main repo. But looks like will be useful for someone having similar requirement. 

I will build upon this pull request with example and documentation if you are interested.

PS : This also fixes one of the problem in autoplay where slide always changes based on interval time set even if user is interacting with the slides. Ideally time should reset if user has changed the slide himself.

### CODE REVIEW

**Comment by akiran** [comment]
We might not support per slide autoplaySpeed at the moment.

**Comment by akiran** [comment]
@vishwanatharondekar Thanks for the PR.

I incorporated your remaining part of the fix in  https://github.com/akiran/react-slick/pull/526

**Comment by vishwanatharondekar** [comment]
No problem. Happy to help. Any particular reason we are not looking at incorporating the feature.

**Comment by akiran** [comment]
We trying to closely follow the behaviour of original slick project.
This is not supported in it

**Comment by alexanderfrey** [comment]
Well, then lets make it better !

**Pull request closed without merging**
