### PR TITLE
Make slider and images width responsive with calc(), see #1010

### PR DESCRIPTION
**Pull request by GeorgySerga**
https://github.com/akiran/react-slick/issues/1010

### CODE REVIEW

**Comment by GeorgySerga** [comment]
Hi @laveesingh , I know you can review and merge in this repo, would you please find some time and take a look. Appreciate it, thanks!

**Comment by laveesingh** [comment]
@GeorgySerga sure asap!

**Comment by laveesingh** [comment]
@GeorgySerga I don't think this css solution to the problem will be a good idea. Because if the component doesn't update it's going to create several problems especially with trackLeft. I think forcing component update in the wrapper will be a good idea.
Just add a ref in wrapper:
```
<Slider {...settings} ref={slider => this.slider = slider}> ... </Slider>
```
and doing `this.slider.innerSlider.onWindowResized()` after setting states in wrapper, should take care of the updates.

**Comment by GeorgySerga** [comment]
@laveesingh Hi, thank you for your answer and review. I don't think we understand the problem here the same way. What I'm trying to solve is slider resize in case of no window resize. Some elements on the page open or close, but window resize event wouldn't fire. I haven't seen any problems with this solution, if it doesn't solve all the problems when window size isn't changed, but solve some of them - it's still a solution, I had none of the other issues so far. I'll add a couple of extra gifs to illustrate the point shortly.

**Comment by GeorgySerga** [comment]
Though I think I see what you mean about trackLeft issue, I should also update `transform3D`.

**Comment by laveesingh** [comment]
@GeorgySerga our ultimate plan is to attach a listener to slider resize instead of entire window resize, but we're struggling with that a bit. The problem with pure CSS solution is that we're using calculated values to determine a lot of factors such as trackWidth, listWidth, slideWidth, trackLeft etc and also these values help with consequent results there and if the values aren't correctly updated we may not get desirable visual.
I'd welcome a JS solution.
In fact, I'm reopening the #1010 just to come up with the solution myself.
Thanks for your efforts, though.

**Comment by sag1v** [comment]
>  our ultimate plan is to attach a listener to slider resize instead of entire window resize, but we're struggling with that a bit.

@laveesingh I've done it in #1212 it is waiting for a review (2 months now) :)

**Pull request closed without merging**
