### PR TITLE
Support for React 0.14

### PR DESCRIPTION
**Pull request by vramana**
- Update peerDependecy of react to 0.13 for findDOMNode
- Removed object.assign dependency by using ES7 object spread operator
- IE8 support now requires external polyfill for addEventListener
& removeEventListener. Because using external polyfills is better
than using React's internal library code (**Breaking change**)

Using this release with 0.14 causes errors because findDOMNode is shifted to `react-dom` package. So, to support both 0.14 and 0.13 I chose to go with the error.

### CODE REVIEW

**Comment by vramana** [comment]
@akiran Can you release this as 0.8.0 ??

**Comment by tarkanlar** [comment]
Wow awesome thanks @vramana

**Comment by vramana** [comment]
@tarkanlar You have to live with an error message though.

**Comment by vramana** [comment]
@akiran Can you add me npm collaborators?? So that, I can manage the releases.

**Comment by akiran** [comment]
@vramana Still may people will be using 0.12. We have to support at least two previous versions.

**Comment by vramana** [comment]
@akiran They can stick to the version 0.7.0. Or Alternatively we can update the semver major . So, that their apps continue work fine even if they try to update the dependency. Since semver major can have breaking changes. But many would be pushing 0.14.0-rc in thier production systems. It is not a good idea to hold them back either.

**Comment by tarkanlar** [comment]
@vramana I get this error Error when i try to install with this version. 
with lates version of react 
```  "react": "^0.14.0-rc1",
    "react-addons-create-fragment": "^0.14.0-rc1",
    "react-dom": "^0.14.0-rc1" ```

 Invariant Violation: Objects are not valid as a React child (found object with keys {type, key, ref, _owner, _context, _store}). If you meant to render a collection of children, use an array instead or wrap the object using React.addons.createFragment(object). Check the render method of `Track`.

**Comment by vramana** [comment]
@tarkanlar It is might be due an error due to multiple copies of React. Just check your build tooling once.
Or use npm@3.

**Comment by tarkanlar** [comment]
I've tried with npm @3.3.3 as well i am getting the same error
My package.json is
```
{
  "private": true,
  "engines": {
    "node": ">= 0.10",
    "npm": ">= 2.1"
  },
  "dependencies": {
    "babel": "^5.8.23",
    "babel-core": "^5.8.24",
    "basket.js": "^0.5.2",
    "classnames": "^2.1.3",
    "eventemitter3": "^1.1.1",
    "express": "^4.13.3",
    "fastclick": "^1.0.6",
    "fbjs": "^0.2.1",
    "file-loader": "^0.8.4",
    "flux": "^2.1.1",
    "front-matter": "^1.0.0",
    "git-push": "^0.1.1",
    "ionicons": "^2.0.1",
    "jade": "^1.11.0",
    "lodash": "^3.10.1",
    "memory-cache": "^0.1.4",
    "newforms": "^0.12.1",
    "normalize.css": "^3.0.3",
    "radium": "^0.14.1",
    "react": "^0.14.0-rc1",
    "react-addons-create-fragment": "^0.14.0-rc1",
    "react-dom": "^0.14.0-rc1",
    "react-paginate": "^0.2.0",
    "react-routing": "^0.0.4",
    "react-slick": "vramana/react-slick#react-0.14",
    "replace": "^0.3.0",
    "source-map-support": "^0.3.2",
    "superagent": "^1.4.0"
  },
  "devDependencies": {
    "autoprefixer-core": "^5.2.1",
    "babel-eslint": "^4.0.5",
    "babel-loader": "^5.3.2",
    "browser-sync": "^2.8.2",
    "css-loader": "^0.15.6",
    "csscomb": "^3.1.8",
    "cssnext": "^1.8.3",
    "del": "^2.0.2",
    "eslint": "^1.1.0",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-react": "^3.2.2",
    "gaze": "^0.5.1",
    "glob": "^5.0.14",
    "jest-cli": "^0.5.5",
    "mkdirp": "^0.5.1",
    "ncp": "^2.0.0",
    "postcss": "^4.1.16",
    "postcss-loader": "^0.5.1",
    "postcss-nested": "^0.3.2",
    "psi": "^1.0.6",
    "react-hot-loader": "^1.2.8",
    "run-sequence": "^1.1.2",
    "style-loader": "^0.12.3",
    "url-loader": "^0.5.6",
    "webpack": "^1.11.0",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.1.0"
  },
  "jest": {
    "rootDir": "./src",
    "scriptPreprocessor": "../preprocessor.js",
    "unmockedModulePathPatterns": [
      "react"
    ]
  },
  "scripts": {
    "lint": "eslint src tools",
    "csslint": "csscomb src/components --lint --verbose",
    "csscomb": "csscomb src/components --verbose",
    "test": "eslint src && jest",
    "clean": "babel-node --eval \"require('./tools/clean')().catch(err => console.log(err.stack))\"",
    "copy": "babel-node --eval \"require('./tools/copy')().catch(err => console.log(err.stack))\"",
    "bundle": "babel-node --eval \"require('./tools/bundle')().catch(err => console.log(err.stack))\"",
    "build": "babel-node --eval \"require('./tools/build')().catch(err => console.log(err.stack))\"",
    "serve": "babel-node --eval \"require('./tools/serve')().catch(err => console.log(err.stack))\"",
    "start": "babel-node --eval \"require('./tools/start')().catch(err => console.log(err.stack))\""
  }
}
```

**Comment by vramana** [comment]
@tarkanlar Can you clone my repo and run `npm start` after `npm i` and tell me if you get any errors??

**Comment by tarkanlar** [comment]
Yep it works, when i clone your repo.
So it is my fault, I will try to fix my repo.

**Comment by ubien** [comment]
Ran into same Invariant Violation issue- think you just need to rebuild /dist files.

**Comment by hannesj** [comment]
@akiran any update on this, the current version is not working with 0.14-rc1, due to the issue with using EventListener from React internals (which was removed).

**Comment by akiran** [comment]
@tarkanlar, @hannesj   Can you check react-slick@0.8.0
It is working with react@0.14.0-rc1

There are some deprecation warnings which I will fix in next release

**Comment by tarkanlar** [comment]
@akiran 0.8.0 yeah there are warnings  but working fine for me.

**Pull request closed without merging**
