### PR TITLE
Add fix for arrows not working in fade mode

### PR DESCRIPTION
**Pull request by gautamz07**
Fixes issue #1881

### CODE REVIEW

**Comment by gautamz07** [comment]
Fixes issue #1881

**Comment by akiran** [comment]
@gautamz07 this is the actual fix for #1881 
https://github.com/akiran/react-slick/pull/1890

currentSlide and targetSlide have subtle differences.
They are especially apparent in focusOnSelect and infinite mode.  Most of my recent fixes are for these modes

**Comment by gautamgoshopmatic** [comment]
@akiran alrighty , great !

**Comment by marlongichie** [comment]
This issue seems to still exist. Was there a solution available?

Thanks

**Pull request closed without merging**
