### PR TITLE
Fixed out of bounds exception

### PR DESCRIPTION
**Pull request by silicakes**
When the slides pulled 'outside' the screen - an exception occurs. 
This fixes it.

For more information see: issue #736

### CODE REVIEW

**Comment by laveesingh** [comment]
I don't think there's any issue like this. I tried to reproduce on codesandbox demo, but I couldn't.

**Comment by silicakes** [comment]
Just reproduced it:
https://codesandbox.io/s/zx03wppno3
feb-05-2018 12-28-40

**Comment by silicakes** [comment]
@laveesingh - fixed the conflicts, feel free to merge.

**Comment by laveesingh** [comment]
@silicakes I'd love to merge effective changes, but I'm still struggling to regenerate it locally on my chrome.

**Comment by silicakes** [comment]
Is there a way for me to help?

**Comment by laveesingh** [comment]
@silicakes #614  has been merged, which fixes the issue.

Thanks a lot for the efforts.

**Pull request closed without merging**
