### PR TITLE
Fix `slick-initialized` to fire when the component finishes mounting …

### PR DESCRIPTION
**Pull request by chemoish**
…(Only fires on the client). This will prevent a FOUC when doing SSR.

NOTE: https://github.com/akiran/react-slick/blob/master/src/initial-state.js#L27 seems like dead code.

### CODE REVIEW

**Comment by chemoish** [comment]
Addresses https://github.com/akiran/react-slick/issues/254.

**Comment by chikathreesix** [comment]
Works great! Hiding the component is definitely better than FOUC. Ideally I'd like to prepare the space for the carousel and show a loading indicator in there.

**Comment by chemoish** [comment]
@akiran thoughts?

**Comment by chemoish** [comment]
@chikathreesix, for me `slick-initialized` is just wrong as it currently stands and should be fixed. #imo

**Comment by chikathreesix** [comment]
@chemoish I see your point. I have also tried a different approach after I commented here #288

**Comment by akiran** [comment]
Closing this because add classes with classList.add is not a very react friendly
I might consider merging #288

**Comment by chemoish** [comment]
Do you have documentation that indicates your statement is the case?

In my experience this is the most performant way of managing visibility. Alternatively, you can have a `getInitialState` and a `setState` that manages this information—it will cause a double render, but the virtual DOM should make the hit trivial.

Either solution is better than #288—due in part to the complexity of the solution, but also the current logic is incorrect (The slider isn't initialized until the component finishes mounting).

**Comment by chikathreesix** [comment]
The reason why I created #288 is, this solution hide the whole carousel so it still causes a layout change after the code runs. The logic of #288 is not complicated, it just hides non current banners. What makes it not really beautiful is handling duplicated banners placed on both left and right. In my opinion, the carousel should take another approach not to generate these backup banners but this is a different topic so I have just dealt with it in a not really beautiful way.

**Pull request closed without merging**
