### PR TITLE
Fix major problems in 0.9.2

### PR DESCRIPTION
**Pull request by ChrisCinelli**
I spent some time to look on the code on fork of people lately and rebase what it made sense. 
These are fixing some major problems because 0.9.2 is not viable for me. 
This include: https://github.com/akiran/react-slick/pull/182, https://github.com/akiran/react-slick/pull/182, https://github.com/akiran/react-slick/pull/178

There are still other problems, the biggest one is the one that was supposed to be solve by this PR: https://github.com/akiran/react-slick/pull/30 (I have a fading slider). However this PR makes react-slick almost usable.

I suggest to merge. Until it happen I will keep adding my fixes.

### CODE REVIEW

**Comment by bvasko** [comment]
+1 @akiran perhaps you can solicit another maintainer to, at the very least, help manage PRs? I'm sure I'm not the only using this slider pretty heavily.

**Comment by ChrisCinelli** [comment]
I agree on adding a maintainer.
For the time being this PR is installable with `npm install github:chriscinelli/react-slick --save`

**Comment by akiran** [comment]
I review the PRs today night.

**Comment by reintroducing** [comment]
@akiran Any update on this? I am starting down the path of using this in our code base but I did notice the issue with the fade slider which is a crucial part of our usage of carousels.  It would be nice to get some of these fixes in here for everyone I'm sure.

**Comment by kenaku** [comment]
@akiran please, merge this as soon as possible!

**Comment by akiran** [comment]
I will look into it

**Comment by akiran** [comment]
Continuing the discussion in #203

**Pull request closed without merging**
