### PR TITLE
Add dontAnimate argument to slickGoTo method

### PR DESCRIPTION
**Pull request by louisptremblay**
Fixes issue #488
Also fixes the example slickGoTo which wasn't working because it was passing a string instead of a number.

### CODE REVIEW

**Comment by edencorbin** [comment]
Can we get this added to merged, we need this feature!

**Comment by bratva** [comment]
Please, do it

**Comment by Leapfrognz** [comment]
+1 for this. original slick has it, this port needs it too.

**Comment by aperkaz** [comment]
Hi,
Is there any reason why this hasnt been merged yet? 
I do not understand... :slightly_frowning_face:

**Comment by laveesingh** [comment]
Can't support this feature. 
Same functionality can be achieved by managing an additional state in wrapper component.

**Pull request closed without merging**
