### PR TITLE
Adds slickPause() and slickPlay() methods

### PR DESCRIPTION
**Pull request by jeffreznik**
Also adds options to `pauseOnSwipe` and `pauseOnChange` (both default:
false to not break existing sliders).  Removes autoPlayTimer from state
as `this.setState({…})` was being called on every slide change causing
unnecessary re-renders.  Also fixes bug in `update(props)` where
`this.pause()` was being called when autoplay was true.

### CODE REVIEW

**Comment by jeffreznik** [comment]
@akiran can this be merged in?

**Comment by akiran** [comment]
@jeffreznik  Can you remove pauseOnSwipe and pauseOnChange options because there are not part of slick API. 

You can keep slickPause and slickPlay methods

**Comment by xrs1133** [comment]
Can we merge this?

**Comment by jeffreznik** [comment]
I will need to remove the pauseOnSwipe/pauseOnChange options first, as they aren't part of the API... I just haven't had the opportunity to do so (will try to sometime this weekend).

**Comment by xrs1133** [comment]
@jeffreznik I added a PR that piggy backs on yours that removes the props. I hope that is ok by you.

**Comment by jeffreznik** [comment]
Yes that is fine by me (saves me work :)), thanks.

**Comment by akiran** [comment]
Thanks @jeffreznik  for PR
I will merge @xrs1133 PR soon

**Comment by xrs1133** [comment]
👍

**Comment by xrs1133** [comment]
I will change the title to reflect @jeffreznik original PR

**Comment by msalsas** [comment]
@akiran Will you merge this PR? I also need the slickPause functionality. Thanks.

**Comment by xrs1133** [comment]
@msalsas good luck. I ended up just using my branch.

**Comment by laveesingh** [comment]
`slickPause` and `slickPlay` methods have been taken into consideration. These will be added very soon. But unfortunately, this PR cannot be merged due to undesired `pauseOnSwipe` and `pauseOnChange` properties.

**Comment by msalsas** [comment]
@laveesingh, @xrs1133 has fixed it at [https://github.com/xrs1133/react-slick](https://github.com/xrs1133/react-slick)

**Comment by laveesingh** [comment]
@msalsas Here is the PR for that: https://github.com/akiran/react-slick/pull/605
But that couldn't get merged either because that included unwanted `lib` directory.

**Comment by msalsas** [comment]
@laveesingh Is it all? Can I help?

**Comment by laveesingh** [comment]
@msalsas major intention of these two PRs was to get `slickPause` and `slickPlay` included. The properties have been taken in and will be merged to master once @akiran has done reviewing it.
As we can see there are hundreds of issues that need to be resolved, you are most welcome to send PRs or create new issues if you find any.

**Pull request closed without merging**
