### PR TITLE
Better formatting + ES6

### PR DESCRIPTION
**Pull request by vramana**

### CODE REVIEW

**Comment by akiran** [comment]
@vramana I think we should not class syntax of react to support react 0.12 users.
We can use it in future.

Can you revert the changes to React.createClass

**Comment by vramana** [comment]
Reverted.

**Comment by vramana** [comment]
@akiran This line https://github.com/akiran/react-slick/blob/master/lib/initial-state.js#L32 
` // $prevArrow: null,` is under removed.
 So, is this line https://github.com/akiran/react-slick/blob/master/lib/inner-slider.jsx#L141 relevant ??
`var prevArrow = <this.props.prevArrow {...prevArrowProps} />;`

**Comment by akiran** [comment]
Yes  https://github.com/akiran/react-slick/blob/master/lib/inner-slider.jsx#L141  is relevant.   It default value is at https://github.com/akiran/react-slick/blob/master/lib/default-props.js#L36

**Pull request merged**
