### PR TITLE
Fix bug: item is invisible when vertical & fade are true simultaneously

### PR DESCRIPTION
**Pull request by valleykid**
#974

### CODE REVIEW

**Comment by laveesingh** [comment]
The pr fixes the issue when `slidesToShow: 1`. However, if `slidesToShow > 1`, all the slides except the first one, remain invisible.

**Comment by valleykid** [comment]
OK，I see. but I don't know how do these slides switch and show when `slidesToShow > 1`, please help me. thanks~

**Comment by laveesingh** [comment]
@valleykid we figured that having `slidesToShow > 1` causes a lot of problems so we're enforcing `slidesToShow = 1` when `fade` is true. In that case, I'll merge your PR asap.

**Comment by valleykid** [comment]
It's not a bad idea. Please merge the PR asap because [antd-carousel](https://ant.design/components/carousel) depends.
Thank you very much~

**Comment by laveesingh** [comment]
It's been merged into the dev branch, and the dev branch should be merged into master by the weekend (hopefully).

**Pull request merged**
