### PR TITLE
fullscreen added

### PR DESCRIPTION
**Pull request by watzak**
This functionality provides fullscreen mode for images! 

screen shot 2017-10-23 at 15 08 53

screen shot 2017-10-23 at 15 09 02

### CODE REVIEW

**Comment by dmosyash** [comment]
Please show an example how to implement fullscreen in the library

**Comment by watzak** [comment]
Hi @dmosyash 

I just updated the example! Check latest commit https://github.com/akiran/react-slick/pull/893/commits/2af32e9b0df0366f16a270818f6a237216d19c95 

U have to include an attribute fullscreenArrow: <FullScreenArrow /> in react-slick options!
Then u have to specify your fullscreen link in FullScreenArrow Component! I also included default link style into docs/_style.scss!
But u can modify your fullscreen button, href html like u want! Same with the stylesheets!

Hope that helps u!
Cheers

**Comment by watzak** [comment]
Hello @akiran 

Is this functionality (fullscreen mode) something u want to include into your master?
If yes, when do u think u are able to merge it? I know we developer are all busy and have 100s projects beside this, but when do u think it's manageable for u?

Thanx in advance for your feedback!

Cheers watzak

**Comment by laveesingh** [comment]
We would love to have features like this in future. But currently, our prime goal is to be similar to and not to deviate from [slick](https://github.com/kenwheeler/slick) library. For now, I'm closing this, but once we are close enough to our goal, we'd definitely wanna have features like this.
Thanks a lot for the PR.

**Pull request closed without merging**
