### PR TITLE
fix, a moving in opposite direction on drag event at rtl option

### PR DESCRIPTION
**Pull request by ignocide**
i found problem at rtl option,
when drag a object, that moving in opposite direction,
you can check at example

### CODE REVIEW

**Comment by nimatrueway** [comment]
good job, but still incorrect behavior on first/last items when `infinite: true`.

**Comment by laveesingh** [comment]
Thanks, @ignocide, and @nimatrueway 
That solves the mentioned problem, the pr will be merged Shortly

**Comment by Linton-Samuel-Dawson** [comment]
I've installed react-slick with `npm` and still have this problem

**Comment by caprica-Six** [comment]
Same here, even if direction is set to rtl: true, seems to render dir="ltr"...

**Pull request merged**
