### PR TITLE
removing usage of unsafe componentWillReceiveProps

### PR DESCRIPTION
**Pull request by aakula-edmunds**
avoid React 16 deprecation warnings: get rid of unsafe componentWillReceiveProps

### CODE REVIEW

**Comment by aakula-edmunds** [comment]
Hello, I see CI build fails because of Jest issue - https://github.com/facebook/jest/issues/8069, this happened after Node v11.11
I tried to apply a temporary workaround - downgrade Node to 11.10.1 in .travis.yml file but unfortunately, travis-ci goes on with the previous version of .travis.yml  (https://travis-ci.org/akiran/react-slick/jobs/505291247/config)

**Comment by gasp** [comment]
this duplicates https://github.com/akiran/react-slick/pull/1443

**Comment by aakula-edmunds** [comment]
> this duplicates #1443
What do you mean? 
My PR does not touch `componentWillMount`

**Comment by gasp** [comment]
My mistake, I read the PR too quickly, sorry !

**Comment by karesh** [comment]
Is it fixed  ? "index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code."

**Pull request closed without merging**
