### PR TITLE
fix mobile scroll

### PR DESCRIPTION
**Pull request by Hermanya**
This patch prevents scrolling and swiping at the same time.

### CODE REVIEW

**Comment by kulor** [comment]
@Hermanya tried your fork, works perfectly!

**Comment by Hermanya** [comment]
@kulor I have a feeling this is not gonna be merged, `npm install react-slick-with-mobile-in-mind` is my fork

**Comment by kulor** [comment]
@Hermanya really useful, will use your fork until this is merged.

**Comment by semenets** [comment]
Excellent, hope someone will merge that :)

**Comment by chiplay** [comment]
@akiran any chance this will get merged? I'd love to keep using the core project and not the outdated fork. Thanks!

**Comment by SrSandeepKumar** [comment]
i tried using `npm install react-slick-with-mobile-in-mind` react-slick's like UI disappeared. 
Observations on mobile device:
0. Image flickering effect did not appear using this.
1. Got numbers instead of dots.
2. Slide images were smaller.

**Comment by laveesingh** [comment]
Similar issues have already been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.

**Pull request closed without merging**
