### PR TITLE
Finite variable width slider slides always fill the display area

### LINKED ISSUE #1334: Finite variable width slider (that scrolls only visible slides), slides should always fill the display area
>I hope this is not a "big ask" but I'm stuck and I love your library as it has helped me a lot in the past.

## Overview
My issue is that I'm trying to adjust the [variable width](https://react-slick.neostack.com/docs/example/variable-width/) slider (in your documentation) in order to be:
1. `finite`
2. `responsive` (to different viewports) (if possible to display as many slides according to viewport width)
3. `scroll only 100% visible slides`
4. slides should fill the `div` display area

### Observations

1. So far, I have managed to make it:
   - `finite`

2. Regarding `responsive`, breakpoints don't work well for `variable width` slides.

3. `scroll only 100% visible slides`, This is very important when it comes to variable viewport width and when using variable width slides.

4. `slides should fill the`**div**`display area`, _finite variable width slides_ when they reach the last slide, even though it was already visible by the previous scroll, the user can still scroll and what is visible is a huge area of blank slides, for example:
blank slides visible after last slide

## The Code
The issue can be replicated and tested in [code sandbox](https://codesandbox.io/s/983v21ooq4)

> I'm open to hear your expert solutions.

### PR DESCRIPTION
**Pull request by diegopamio**
Fixes #1334

I've added some logic to snap the right side of the last slide to the right side of the scrolling window.

### CODE REVIEW

**Comment by cgadam** [comment]
This is nice @diegopamio! Please consider the case when there are few items in the carousel. I can see a bug in this case where the few items (in this case just 2) get aligned to the right instead of left as they are supposed to!

See GIF:
csqm77ty3l

**Comment by diegopamio** [comment]
@cgadam done, now it doesn't snap to the right if the width of all the available images is less than the width of the container.

**Comment by bgoldfarb** [comment]
What is the status of this PR? @diegopamio

**Comment by pinglinh** [comment]
Yeah I agree with @precompiled! This needs to be resolved too :/

**Comment by ydegtyar** [comment]
Will it be merged?

**Comment by groomain** [comment]
Will it be merged one day ? 🙏

**Comment by diegopamio** [comment]
I'm having little to nothing free time for this, If anyone can help on @precompiled request, or if we can do it separately, I can collaborate.

**Comment by groomain** [comment]
I've finally switched to swiper. Thanks !

**Comment by Charlie91** [comment]
@diegopamio, Hi! I faced the same problem that this PR solves, and wouldn't mind to finish your job. Could you add me to collaborators of the fork so I could add commits here?

**Pull request closed without merging**
