### PR TITLE
Added accessibility (tab and arrow key navigation)

### PR DESCRIPTION
**Pull request by krlospelaez**
Add tab and arrow key navigation

### CODE REVIEW

**Comment by creatifyme** [comment]
@akiran any possibility this will be merged in soon?

**Comment by xiwcx** [comment]
@akiran, hi @krlospelaez and I work at @natgeo and your package has been a huge help to us. we do need this functionality in order to meet business needs and we'd love to get back on the main branch of this project rather than our fork? aside from addressing the conflicts that have emerged since this was first submitted is there anything we can do to make this more likely to be accepted?

thanks much.

**Comment by akiran** [comment]
@krlospelaez Can resolve merge conflicts and not include dist files in PR ?
I will merge it to master today

**Comment by creatifyme** [comment]
@krlospelaez @xiwcx I too need this PR for a current project. Any chance you two could resolve the conflicts in the next couple of days? and hopefully @akiran can merge it in this week 😄

**Comment by krlospelaez** [comment]
@akiran @creatifyme  @xiwcx This is ready to ship :smiley:

**Comment by i8ramin** [comment]
Can we please merge this in? we are also waiting for this functionality. Currently pointing directly to @krlospelaez's fork, but would rather use the official repo. Thank you.

**Comment by creatifyme** [comment]
@akiran any update to when this might be merged in to master?

**Comment by akiran** [comment]
I will review this and merge this week

**Comment by akiran** [comment]
I tried this fix. It didn't work for me

Can any confirm if it works for you

**Comment by GLosch** [comment]
@akiran on our app, left/right arrow navigation only works if you click to focus on the carousel first. Otherwise, it doesn't work

**Comment by brownsmith** [comment]
Any update to this? I'm only able to tab to the next/prev arrows only too

**Pull request merged**
