### PR TITLE
Make centerPadding responsive

### PR DESCRIPTION
**Pull request by renddiyeh**

### CODE REVIEW

**Comment by akiran** [comment]
@renddiyeh Can you remove dist file from PR

**Comment by renddiyeh** [comment]
@akiran just merged with the latest code.
and i added sidePadding feature for my project, you can decide whether to keep this feature or not.

**Comment by akiran** [comment]
centerPadding is already working with the code in master
https://github.com/akiran/react-slick/blob/master/examples/CenterMode.js

screen shot 2016-09-07 at 6 40 05 pm

If this PR is only adding centerPadding, I can close this because it is already working

**Comment by renddiyeh** [comment]
oh, yeah, it seems worked perfect now.
ok, let's just close this PR.

**Comment by akiran** [comment]
Thanks @renddiyeh

**Pull request closed without merging**
