### PR TITLE
Fix slide width issue by transform scale

### PR DESCRIPTION
**Pull request by afc163**
close ant-design/ant-design#3659

The element'width will be affected by `transform: scale(xxx)`.

https://codepen.io/afc163/pen/RxNbQq?editors=0110

### CODE REVIEW

**Comment by afc163** [comment]
ping~

**Comment by orangeyyy** [comment]
I have got the same problem, but why this MR didn't merge to the master?

**Comment by orangeyyy** [comment]
I really have this situation, please merge this MR to the master

**Comment by afc163** [comment]
ping~

**Comment by laveesingh** [comment]
The PR has been taken into account. Merged changes will be released soon.
Thanks for your effort.

**Pull request merged**
