### PR TITLE
Support disable bounce for vertical mode

### PR DESCRIPTION
**Pull request by alziqziq**
Thanks for great library 👍 
-
from this commit https://github.com/akiran/react-slick/commit/38d16a9f567d37ee6c6a6cfdba6c3db76bfaed9d only supports horizontal mode, I added for vertical mode, we also need it in vertical mode.

### CODE REVIEW

**Comment by alziqziq** [comment]
Hi, @akiran
can you consider this pull request? thanks 🙏

**Comment by muhammadalifsyafri** [comment]
This is exactly what I needed at the moment! looking forward to the review! @akiran

**Review by akiran — APPROVED** [review]

**Comment by akiran** [comment]
@alziqziq  @muhammadalifsyafri  Merged this PR and released 0.28.1

**Comment by alziqziq** [comment]
thanks @akiran 🕺 🕺 🕺

**Comment by muhammadalifsyafri** [comment]
thanks for the approval! @akiran 🎉

**Pull request merged**
