### PR TITLE
Fix extra setInterval when autoplay

### LINKED ISSUE #285: setInterval every switch without clearing when autoPlay
Cause issue after react-slick is ummounted.

```
warning.js?0260:44 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the InnerSlider component.
```

version: 0.11.1

https://github.com/ant-design/ant-design/issues/1397#issuecomment-209340907

---

https://github.com/akiran/react-slick/commit/9bbe0fa9191bb5b1156cec4755532ee108f14cbc

Why use `setInterval` instead `setTimeout`, `setInterval` will repeat forever, and never clear it when it switch automaticly!! And `componentWillUnmount` can only clear one last interval (there are many intervals).

### PR DESCRIPTION
**Pull request by afc163**
close #285 and ant-design/ant-design#1397

### CODE REVIEW

**Comment by afc163** [comment]
ping~ @akiran

**Comment by kairi1227** [comment]
please fix~~~thx.

**Comment by Mn0491** [comment]
@afc163  is there anyway I can implement your fix for the time being? @akiran doesn't seem to be responding

**Comment by akiran** [comment]
I will review this today

**Comment by afc163** [comment]
😿

**Comment by akiran** [comment]
This broke the pauseOnHover feature of autoplay.
I need to fix it before publishing this change to npm

**Comment by kairi1227** [comment]
@akiran please fix ~~~~ thx!!!!

**Comment by afc163** [comment]
🎉

**Comment by akiran** [comment]
React 0.12.1 with this fix

**Pull request merged**
