### PR TITLE
Fixing next button disable state.

### PR DESCRIPTION
**Pull request by suheb**
Fixes https://github.com/akiran/react-slick/issues/271
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>

### CODE REVIEW

**Comment by suheb** [comment]
@akiran Let me know if anything else is required. Thanks.

**Comment by suheb** [comment]
Please review this @akiran, desperately need this merged.

**Comment by akiran** [comment]
There is issue with center mode when number of slides is equal to slidesToShow. empty space is appearing on left side.

screen shot 2016-09-06 at 11 15 07 pm

Need to fix it before merging this

**Comment by suheb** [comment]
@akiran I think that's a separate issue from this. I reverted these changes and the empty space on left side was still appearing.

**Comment by akiran** [comment]
@suheb Sorry for delay in merging this PR.

I merged #430 which fixes the white space issue.
I am little confused about this PR. Can you give settings to replicate the issue this PR fixes

**Comment by suheb** [comment]
@akiran Here's the settings to replicate this:
```
const settings = {
      className: 'center',
      centerMode: true,
      infinite: false,
      centerPadding: '60px',
      slidesToShow: 5,
      speed: 500,
    };
```
Now if you have 6 slides, the next button will be disabled at 2nd slide which is correct when centerMode is false. But when centerMode is true, we should not disable next button until we reach the last slide.

Here's a screenshot of this issue.



Fix:

**Comment by suheb** [comment]
Thanks :+1:

**Pull request merged**
