### PR TITLE
Fix issue where animation transition events do not get triggered.

### PR DESCRIPTION
**Pull request by dcocchia**
This should fix many issues where the `track` DOM node's transition events do not fire on transitionend, most likely because state changes during animation causes a re-render.

### CODE REVIEW

**Comment by dcocchia** [comment]
A fi for https://github.com/akiran/react-slick/issues/337

**Comment by blairanderson** [comment]
@dcocchia as per contributing guidelines, remove changes to `/dist`

**Comment by dcocchia** [comment]
Will open in a new PR

**Comment by dcocchia** [comment]
Moved to: https://github.com/akiran/react-slick/pull/408

**Pull request closed without merging**
