### PR TITLE
Vertical Mode

### PR DESCRIPTION
**Pull request by Josh-ES**
This build of the project adds working 'vertical' and 'verticalSwiping' properties. This consists of several changes when the 'vertical' property is set to true:

- The height CSS property of the '.slick-list' element is set manually.
- The height of the track is now set based on the number of children and the heights of a child (variableHeight or similar is not yet supported), and the width is not set in this case.

When 'verticalSwiping' is set to true:

- Vertical swiping is now detected correctly by the swipe event handlers, including swipeDirection. This includes the swipe length, min swipe and swipe direction being calculated correctly for vertical swiping. Horizontal swiping is ignored.

### CODE REVIEW

**Comment by akiran** [comment]
@Josh-ES Sorry for delay in reviewing the PR.

I was looking at the vertical demo and started clicking next arrow and when it reach slide 6, slide jumps. Have you noticed it ?

**Comment by Josh-ES** [comment]
I'm trying to respond to this but every time I run the gulp task to build the demo page, the webpack process doesn't produce any errors, but doesn't output the expected "docs.js" file either. Any ideas as to what might be causing this?

**Comment by akiran** [comment]
I am testing on chrome browser and MAC.
It works most fine and just little jump at the last slide.  I will try to debug it today and let you no know my findings.

Thanks for the nice work in adding this feature

**Comment by akiran** [comment]
Strangely I couldn't replicate the jump issue now. Its working perfectly.

I merge it and I will make a release soon

**Comment by Josh-ES** [comment]
Many thanks, let me know if that issue crops up again.

I have a branch ready with SwipeToSlide functionality. I know that #265 has already implemented this, but I've made sure SwipeToSlide works properly with vertical mode enabled (which it doesn't in the original library, nor in that PR). Shall I submit another pull request given one already exists?

**Comment by akiran** [comment]
Yes, your PR will be good since it works with vertical mode as well

**Pull request merged**
