### PR TITLE
Enable click event even when the swipe option is false

### PR DESCRIPTION
**Pull request by RyoIkarashi**
https://github.com/akiran/react-slick/issues/547

### CODE REVIEW

**Comment by martinpesout** [comment]
@akiran this PR is also important for use. We have set `swipe` to `false` and cannot click (on touch devices) on elements inside slick slides. This will fix it. Do you think that you can merge it?

Thanks to @RyoIkarashi for this fix.

**Comment by malliapi** [comment]
@akiran I know you must be busy, but is it possible to have a look at seeing if you agree with merging this? Many thanks :-)

**Comment by malliapi** [comment]
ok so to anyone in need of this urgently i have published here https://www.npmjs.com/package/react-slick-2

**Comment by martinpesout** [comment]
Hi, is it possible to merge this PR?

**Comment by laveesingh** [comment]
Similar issues have already been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.

**Pull request closed without merging**
