### PR TITLE
SwipeToSlide

### PR DESCRIPTION
**Pull request by dudarau**
1. Swipe to Slide - Allow user to swipe with indeterminate step
2. Don't swipe farther then last slide

### CODE REVIEW

**Comment by valeryq** [comment]
What about PR?

**Comment by jakeaaron** [comment]
Thanks so much for this React port of the slick carousel!
Would love to see this feature implemented!

**Comment by Tamiyadd** [comment]
this pull request is working great, can we merge it so i can use directly from this repo? thanks

**Comment by akiran** [comment]
Merged #463 which implements this feature

**Comment by Tamiyadd** [comment]
thanks!

**Pull request closed without merging**
