### PR TITLE
Fix IE8 Compatibility

### PR DESCRIPTION
**Pull request by nosir**
- Add matchMedia polyfill for README
- Fix addEventListener issue
- Fix empty array map issue

### CODE REVIEW

**Comment by vramana** [comment]
@nosir Have you tested this in IE8?

**Comment by akiran** [comment]
Thanks to @nosir,  @sorrycc for trying to add support for IE8

@sorrycc Can you review this.
If it is fine, we will merge it and make a release soon

**Comment by nosir** [comment]
@vramana yes, i've tested on native IE8

**Comment by vramana** [comment]
Can you merge your commits into one? 

What about map? We have to put a notice to use es5-shim I guess.

**Comment by nosir** [comment]
Merged to one.
map is working fine now, just filled the empty array first, please see the comment in dots.jsx
es5-shim is mentioned as a must thing for IE8 in ReactJS doc, otherwise the whole ReactJS doesn't load, so I guess it is not that necessary here.

One thing, I had problem setting up babel /webpack dev server on my home laptop, so I made change and tested within the distributed file in master, which should be the same. But if it's easy for you, would be nice if you guys can help generate the final js again and send me for testing. cheers.

**Comment by akiran** [comment]
@nosir I merge the PR and generated dist files.
https://github.com/akiran/react-slick/tree/master/dist

I didn't have ie8 to test
If you can confirm, I will release it on npm

**Comment by nosir** [comment]
Tested, all good. Thanks

**Comment by nosir** [comment]
Thanks for updating, I didn't go for polyfill because ReactJS was differentiating the event usage by checking if `window.addEventListener` exists in dom. Not sure if they have changed this in ReactEventListener, will check later.

**Comment by cytGitHub** [comment]
hellow , which version can support IE8 ?

**Pull request merged**
