### PR TITLE
Support `focusOnSelect` fixes #51

### LINKED ISSUE #51: How to select an Item onClick or Ontap
I would like to use this, but need support for onClick and onTap event. When clicked that item should be selected. I see a option focusOnselect but it not seems to work
screenshot from 2015-05-18 16 09 08
like in following image

### PR DESCRIPTION
**Pull request by scriptype**
- Add an example of focusOnSelect usage to demos
 - Update supported properties table
 - Use ReactDOM on rendering demos

### CODE REVIEW

**Comment by banomaster** [comment]
Why is this not i master branch yet? Thanks for your answer 👍

**Comment by suheb** [comment]
@akiran @scriptype Is this going to be merged? If not, is there a to use this patch with the npm package?

**Comment by scriptype** [comment]
@suheb I'm not sure, thread seems dead.

You can take a look at my forked version which has this feature implemented: https://github.com/scriptype/react-slick

It dates to this issue, not fetched from upstream since then. You may encounter unexpected bugs.

If you want to install it with npm, this should work:
```
npm install git@github.com:scriptype/react-slick.git
```

**Comment by suheb** [comment]
Oh didn't know you could install github forks with npm like this. I'll incorporate your changes in a updated fork of my own. Thanks!

**Comment by akiran** [comment]
I will merge it in this week

**Comment by akiran** [comment]
@scriptype Can you resolve merge conflicts

**Comment by suheb** [comment]
I have merged this patch in my fork but still couldn't get it to work. Was getting `Uncaught Error: Cannot find module 'react-slick'` after installing it directly from github.
I can open a new PR for this patch if it'll help to speed up the process.

**Comment by akiran** [comment]
@suheb Sure. Go ahead with PR.
Please test the fix and don't include dist files in PR

**Comment by suheb** [comment]
@akiran Here you go https://github.com/akiran/react-slick/pull/418/

**Comment by akiran** [comment]
Couldn't merge this because of merge conficlts. But PR made by @suheb  with this logic is merged

**Pull request closed without merging**
