### PR TITLE
fixed centerMode strange padding and added SidePadding feature for convenience

### PR DESCRIPTION
**Pull request by renddiyeh**

### CODE REVIEW

**Comment by akiran** [comment]
@renddiyeh we already have centerPadding.  why do we need sidePadding option ?

**Comment by akiran** [comment]
@renddiyeh We are trying to follow, API of slick
http://kenwheeler.github.io/slick/

Since sidePadding option is not present in slick, we can't add it

**Comment by renddiyeh** [comment]
OK, i understand that slick don't need SidePadding.
For the CenterMode, i'm trying to fix is the miscalculation of width, as you can see from current example, CenterMode isn't centerd.
image

And my fix is like this
image

This is more like CenterMode supposed to be.
I can send a PR just for CenterMode correction.

**Comment by akiran** [comment]
Yes please send a PR for that fix

**Pull request closed without merging**
