### PR TITLE
change class component to functional component

### PR DESCRIPTION
**Pull request by drdah123**
use functional component and its hooks

### CODE REVIEW

**Comment by akshayjai1** [comment]
Good initiative!

**Comment by afc163** [comment]
Could you send this to https://github.com/ant-design/react-slick ?

**Comment by drdah123** [comment]
> Could you send this to https://github.com/ant-design/react-slick ? I will handle it.

how to send this to you? I tried but it's sent to the basic repository

**Comment by akiran** [comment]
Examples in this repo are converted to function components.
We will update the documentation next week.

**Pull request closed without merging**
